/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   '#55695d',
        'primary-dim':               '#495d51',
        'primary-fixed':             '#d2e8d9',
        'primary-fixed-dim':         '#c4dacb',
        'on-primary':                '#ffffff',
        'on-primary-fixed':          '#304339',
        'on-primary-fixed-variant':  '#4c6055',
        'on-primary-container':      '#43564b',
        'primary-container':         '#d2e8d9',
        'inverse-primary':           '#e8fff0',
        'surface-tint':              '#55695d',

        'secondary':                 '#4a6975',
        'secondary-dim':             '#3e5d69',
        'secondary-fixed':           '#c7e8f6',
        'secondary-fixed-dim':       '#b9d9e8',
        'on-secondary':              '#ffffff',
        'on-secondary-fixed':        '#24434f',
        'on-secondary-fixed-variant':'#41606c',
        'on-secondary-container':    '#375662',
        'secondary-container':       '#c7e8f6',

        'tertiary':                  '#835d35',
        'tertiary-dim':              '#75512b',
        'tertiary-fixed':            '#fac898',
        'tertiary-fixed-dim':        '#ebbb8c',
        'on-tertiary':               '#ffffff',
        'on-tertiary-fixed':         '#4c2d0a',
        'on-tertiary-fixed-variant': '#6c4924',
        'on-tertiary-container':     '#62401c',
        'tertiary-container':        '#fac898',

        'background':                '#fffbff',
        'on-background':             '#39382f',

        'surface':                   '#fffbff',
        'surface-dim':               '#e6e3d5',
        'surface-bright':            '#fffbff',
        'surface-variant':           '#ece8db',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#fdf9ef',
        'surface-container':         '#f7f3e8',
        'surface-container-high':    '#f1eee2',
        'surface-container-highest': '#ece8db',
        'inverse-surface':           '#0f0e0a',
        'inverse-on-surface':        '#9f9d96',
        'on-surface':                '#39382f',
        'on-surface-variant':        '#66655a',

        'outline':                   '#838175',
        'outline-variant':           '#bcb9ad',

        'error':                     '#af3d3b',
        'error-dim':                 '#67040d',
        'error-container':           '#fa746f',
        'on-error':                  '#ffffff',
        'on-error-container':        '#6e0a12',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.375rem',
        lg:      '0.5rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body:     ['Work Sans', 'sans-serif'],
        label:    ['Work Sans', 'sans-serif'],
        script:   ['Great Vibes', 'cursive'],
      },
    },
  },
  plugins: [],
};
